services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: weathercast-php
    ports:
      - "8080:80"
    volumes:
      - /home/imply/Área de Trabalho/Desafio-imply2:/var/www/html
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo pdo_mysql mysqli && a2enmod rewrite && apache2-foreground"
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: weathercast-sql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
