CREATE DATABASE IF NOT EXISTS ClimaDB
    DEFAULT CHARACTER SET = 'utf8mb4';

USE ClimaDB;

CREATE TABLE IF NOT EXISTS Clima(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Temperatura FLOAT NOT NULL,
    Umidade INT NOT NULL,
    Vento FLOAT NOT NULL,
    Sensacao FLOAT NOT NULL,
    Descricao VARCHAR(320)
);

CREATE TABLE IF NOT EXISTS Historico(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DataHora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,    
    ClimaID INT NOT NULL,
    Cidade VARCHAR(255) NOT NULL,
    FOREIGN KEY (ClimaID) REFERENCES Clima(ID)
);


DROP DATABASE ClimaDB;
