CREATE DATABASE IF NOT EXISTS ClimaDB
    DEFAULT CHARACTER SET = 'utf8mb4';

USE ClimaDB;

CREATE TABLE IF NOT EXISTS Historico(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATETIME CURRENT_TIMESTAMP NOT NULL,    
    Foreign Key (ClimaID) REFERENCES CLima(ID)
);

CREATE TABLE IF NOT EXISTS Clima(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Temperatura FLOAT NOT NULL,
    Umidade INT NOT NULL ,
    Vento FLOAT NOT NULL,
    Sensação FLOAT NOT NULL,
    Descrição VARCHAR(320)
);
